### ISSUE TITLE
error - ReferenceError: window is not defined. How to fix this bro

### ISSUE THREAD

**Issue by carosaome** [loopmode/react-nipple#57]
error - ReferenceError: window is not defined
    at C:\Users\Thinkpad\Desktop\CodeSpace\thinkshare-browser\node_modules\nipplejs\dist\nipplejs.js:5:36
    at C:\Users\Thinkpad\Desktop\CodeSpace\thinkshare-browser\node_modules\nipplejs\dist\nipplejs.js:1:88
    at Object.<anonymous> (C:\Users\Thinkpad\Desktop\CodeSpace\thinkshare-browser\node_modules\nipplejs\dist\nipplejs.js:1:324)
    at Module._compile (node:internal/modules/cjs/loader:1105:14)    
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)     
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (C:\Users\Thinkpad\Desktop\CodeSpace\thinkshare-browser\node_modules\react-nipple\lib\ReactNipple.js:16:17) {   
  page: '/'
}

**Comment by carosaome** [comment]
i think bug happend cuz conflict between React 16 vs React 18

**Comment by xih** [comment]
@carosaome running into the same error. 

Did you have a fix?

**Comment by carosaome** [comment]
@xih Hi, I've use another library. You can checkout https://www.npmjs.com/package/react-joystick-component.
Hope it fit in your problem

**Comment by xih** [comment]
Sweet, thanks for linking that! Checking it out now
